package Assignment_2;

//Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;

import org.testng.annotations.AfterClass;
import org.testng.annotations.BeforeClass;
import org.openqa.selenium.JavascriptExecutor;

import java.util.*;

public class LoginTestTest {
	WebDriver driver ;

// exported script from Selenium IDE -
	
	
	@Test
	public void loginTest() {
		System.setProperty("webdriver.chrome.driver", "C:\\chromedriver.exe");// chrome driver location
		 driver = new ChromeDriver();// Intializing driver
		driver.get("http://demo.guru99.com/test/newtours/");
		driver.manage().window().setSize(new Dimension(1022, 726));
		driver.findElement(By.name("userName")).click();
		driver.findElement(By.name("userName")).sendKeys("mercury");
		driver.findElement(By.name("password")).sendKeys("mercury");
		driver.findElement(By.name("submit")).click();
		assertThat(driver.findElement(By.cssSelector("h3")).getText(), is("Login Successfully"));
		driver.findElement(By.linkText("Flights")).click();
		{
			String value = driver.findElement(By.name("fromPort")).getAttribute("value");
			assertThat(value, is("Acapulco"));
		}
	}
}
